### ISSUE TITLE
[FEAT]: Allow importing individual flag components

### ISSUE THREAD

**Issue by glominashvili** [shinokada/svelte-flag-icons#2]
### Description

Hi,

I'm using only few flags from the library, but during the build, all flags get built. One solution to this is to allow individual component imports.
Instead of  `import { Us, Ca, Fr, De, Dk, Jp, No, Ch, Cz } from 'svelte-flag-icons';`
import individually: `  import Jp from 'svelte-flag-icons/dist/Jp.svelte'';`
[Example from different project](https://github.com/metonym/svelte-bootstrap-icons#direct-import-recommended)
I removed this section from the `package.json`:
```
	"exports": {
		".": {
			"types": "./dist/index.d.ts",
			"svelte": "./dist/index.js"
		}
	},
```
And it worked for both kind of imports.

Can you please add this to the project?

**Comment by shinokada** [comment]
How do you know that "during the build, all flags get built"?

**Comment by glominashvili** [comment]
These are build times, before and after I made changes and imported individually:
![before](https://user-images.githubusercontent.com/2003039/222959276-3c3f304d-ea60-43fd-90d2-df68de509351.png)
![after](https://user-images.githubusercontent.com/2003039/222959279-699e22fd-3a63-41ad-a1ff-10f608769d96.png)

The size of the compiled files are not different, just number of built files and build time is much higher.

**Comment by glominashvili** [comment]
This is the error when I try to import individually without changes:
```
[commonjs--resolver] Missing "./dist/Ge.svelte" specifier in "svelte-flag-icons" package
error during build:
Error: Missing "./dist/Ge.svelte" specifier in "svelte-flag-icons" package
```

**Comment by shinokada** [comment]
When I remove `exports`, the number of files and time does not change.
Could you please clarify if there is anything that I might be overlooking or not understanding correctly?

Can you tell me the version for svelte-flag-icons?

**Comment by glominashvili** [comment]
Did you also rewrite imports to import individually? Like shown above?
If you only remove "exports" nothing will change.
I'm using the latest version.

**Comment by shinokada** [comment]
I just updated it. Can you try the latest and let me know.

**Comment by shinokada** [comment]
I'm not sure if this is the best practice. According to the [SvelteKit packaging docs](https://kit.svelte.dev/docs/packaging#anatomy-of-a-package-json-exports), it is recommended to use exports:

```
{
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "svelte": "./dist/index.js"
    }
  }
}
```

Later on, I will update the export using this (from the docs):

```
{
  "exports": {
    "./Jp.svelte": {
      "types": "./dist/Jp.svelte.d.ts",
      "svelte": "./dist/Jp.svelte"
    }
  }
}
```

So that you can use it like this:

```
import Foo from 'svelte-flag-icons/Jp.svelte';
```

**Comment by glominashvili** [comment]
Thank you very much, I will try it.
I'm not using SvelteKit, just Svelte.
I think it is good to have a choice and reduce the build time.

**Comment by glominashvili** [comment]
@shinokada  Thank you again, I have checked and it works.

**Comment by shinokada** [comment]
I just update and you can use it like this: (without dist)

```
<script lang="ts">
  import Ac from 'svelte-flag-icons/Ac.svelte'
  import Jp from "svelte-flag-icons/Jp.svelte";
</script>

<Ac />
<Jp />
```

Thank you for this issue. I will update all other icon packages as well.

**Comment by shinokada** [comment]
You need to install typescript 5:

```
pnpm i -D typescript@beta
```

And add the following to tsconfig.json:

```
{
    //...
    "compilerOptions": {
        // ...
        "moduleResolution": "bundler"
    }
}
```

**Comment by glominashvili** [comment]
Currently I'm not using TypeScript in my project.
